const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const ctx={React:{createElement:(tag,props,...children)=>({tag,props,children})},window:{addEventListener(){}},document:{getElementById(){}},ReactDOM:{createRoot:()=>({render(){}})},Intl,Date};
vm.createContext(ctx);vm.runInContext(fs.readFileSync('traderbot/dashboard/static/app.js','utf8'),ctx);
const result=ctx.TrendDetails({assessment:{points:12,maximum_points:20,as_of:'2026-09-10T19:55:00Z',components:[{label:'EMA21 slope over five bars',observed:.000552074,threshold:.002,operator:'>=',unit:'ratio',passed:false,available:true,points:0,maximum_points:4}]}});
const rendered=JSON.stringify(result);
for(const text of ['Trend: 12/20','0.0552%','0.2000%','Fail','0/4','Assessed']) assert.ok(rendered.includes(text),text);
assert.ok(JSON.stringify(ctx.TrendDetails({})).includes('Trend breakdown not recorded'));
console.log('Dashboard trend rendering checks passed');

const atr=JSON.stringify(ctx.TrendDetails({assessment:{points:4,maximum_points:20,components:[{observed:.4,threshold:.2,unit:'atr',operator:'>=',passed:true,points:4,maximum_points:4}]}}));
assert.ok(atr.includes('0.4000 ATR')); assert.ok(atr.includes('0.2000 ATR'));
const breakout=JSON.stringify(ctx.BreakoutDetails({assessment:{resistance:100,close:100.75,atr14:1,distance_atr:.75,full_score_atr:.5,maximum_chase_atr:1.5,price_action_points:25,price_action_maximum:25,overextension_points:7.5,overextension_maximum:10,blockers:['breakout_chase_ok']}}));
for(const text of ['Previous-bar ATR 1.0000','Distance 0.7500 ATR','Price action 25/25','Overextension 7.5/10','Breakout exceeds chase limit']) assert.ok(breakout.includes(text),text);
assert.equal(vm.runInContext("healthReason('ema21_slope_positive')",ctx),'EMA21 slope not positive');
assert.equal(vm.runInContext("healthReason('market_regime_favorable')",ctx),'Market regime unfavorable');
const diag=JSON.stringify(ctx.EntryDiagnostics({candidate:{diagnostics:{metrics:{feed:'iex',liquidity_coverage:'single_exchange',quoted_spread_percent:4.31,maximum_spread_percent:.5,matched_intraday_average_dollar_volume:95000,minimum_average_dollar_volume:500000},reentry_policy:{reason:'next_session_setup'}},blockers:['spread_ok']}}));
for(const text of ['Feed: iex','4.31%','0.5%','95,000','500,000','next session setup']) assert.ok(diag.includes(text),text);
const blocked=JSON.stringify(ctx.BlockerConditions({candidate:{blockers:['spread data available','spread ok','breakout chase ok'],breakout_assessment:{distance_atr:2.3159,maximum_chase_atr:1.5},diagnostics:{metrics:{maximum_spread_percent:.5,reasons:['quote_stale','quote_prices_invalid']},submission_validation:{reasons:['execution_chase_limit']}}}}));
for(const text of ['Valid spread data unavailable','Quote is stale','Bid or ask is missing or invalid','Cannot verify spread; maximum 0.5%','2.3159 ATR > maximum 1.5 ATR']) assert.ok(blocked.includes(text),text);
assert.ok(!blocked.includes('Execution ask exceeds chase limit'),'Historical submission must not become a current blocker');
assert.ok(JSON.stringify(ctx.BlockerConditions({candidate:{}})).includes('No recorded blockers'));
const previous=JSON.stringify(ctx.EntryDiagnostics({candidate:{diagnostics:{submission_validation:{checked_at:'2026-09-14T19:29:16Z',reasons:['execution_chase_limit']}}}}));
assert.ok(previous.includes('Last submission check ('));
assert.ok(previous.includes('Execution ask exceeds chase limit'));
